ppw_story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story4.urls')),
    path('story1/', include('story1.urls', namespace='story1')),
    path('story3/', include('story2.urls', namespace='story2')),
    path('story5/', include('story5.urls', namespace='story5')),
    path('story6/', include('story6.urls', namespace='story6')),
    path('story7/', include('story7.urls', namespace='story7')),
    path('story8/', include('story8.urls', namespace='story8')),
    path('story9/', include('story9.urls', namespace='story9')),
]

story1/urls.py
from django.urls import path

from . import views

app_name = 'story1'

urlpatterns = [
    path('', views.index, name='index'),
]

story2/urls.py
from django.urls import path

from . import views
app_name = "story2"
urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about')
]

story2/views.py
from django.shortcuts import render

# Create your views here.

def index(request) :
    return render(request, 'story2/index.html')


def about(request) :
	return render(request, 'story2/about.html')

story2/templates/story2/about.html
{% extends 'story2/index.html'%}
{% load static %}



{% block title %}
<title>About Me</title>
{% endblock %}


{% block css %}
    <!-- Style -->
    <link rel="stylesheet" type="text/css" href="{% static 'story2/style.css' %}">
{% endblock %}
	
<body>

    {% block content %}

    <br>
    <br>
    
    <div class='container text-center' style="min-height: 100vh;">
    	<div class='row no-gutters justify-content-center'>
    		<div class='"col-12 "'>
				<img src="{% static 'story2/JP41.jpg' %} " style="width: 75%; border-radius: 20px; margin-bottom: 5%;">
				
    		</div>
			
    		<div class='col-12 ' >
				<h1 style="margin: auto">Rafi Muhammad</h1>
				<hr style="width: 20%; margin: auto; border-top: 2px solid #000000; margin-top: 2%; margin-bottom: 2%;">
    			<p class="lead"> Computer Science Student </p>
    		</div>

    	</div>

    </div>



    <div class='container text-center'>
    	<div class='row no-gutters justify-content-center'>
    		<div class=col-12>
    			<h1> Little Story About Me</h1>
    			<hr style="width: 20%; margin: auto; border-top: 2px solid #000000;">
    			<br>

    		</div>
    	</div>


    	
    	<div class='row'>
    		<div class=col-12 style="text-align: left;">
    			<p>
    				I'm currently learning computer science at Faculty of Computer Science, University of Indonesia. When I first studying here, I had 0 knowledge about computer science. <br> <br>

    				First semester, I learnt how to code, with Python for the basic, I'm not very good at first so my grade at Foundation Programming 1 is not really good. At that time, I learnt about Discrete Math for basic of programming logic, it was fun subject because it teach you how to think. <br><br>

    				Second semester, I learnt Java. For me, Java is really great when it goes to OOP (Object-Oriented Programming), I understand the concept of OOP when I learn Java, even though I learn it too in Programming Foundation 1 which is using Python. <br><br>

    				Third semester is a chaos, I learn about Data Structure and Algorithm and it is stressing me out, even though it is hard I must give my best at it because it is a foundation to be a Software Engineer, which is one of my career goal. Also I learn about how to making website using Python Django. This website actually part of the task of that subject. I also learn how to code in assembly language that honestly, I don't really like it.
    			</p>
    		</div>
		</div>
		<br>

    </div>

    

    {%endblock%}




</body>
</html>

story2/templates/story2/index.html
{% extends 'story4/base.html'%}

<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>

    {% block title%}
    <title>Profile</title>
    {% endblock %}
    <!-- CSS only -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <!-- JS, Popper.js, and jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1cQRFi3dgfSVKpc1B9idTEuN3cBScszNHP9silYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    
    {% block css %}
    <!-- Style -->
    <link rel="stylesheet" type="text/css" href="{% static 'story2/style.css' %}">
    {% endblock %}
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

    <!--Navbar-->
    <nav class='navbar navbar-expand navbar-custom fixed-top'>
        {% block navbar%}
        <ul class='nav navbar-nav' style="margin-left:auto">

            <li class='nav-item'>
                <a href="{%url 'story2:index' %}"  class='nav-link page-scroll'> Home </a>
            </li>
            
            <li class='nav-item'>
                <a href="{%url 'story2:about' %}"  class='nav-link'> About </a>
            </li>

            <li class='nav-item'>
                <a href="{%url 'story2:index' %}#skills" class='nav-link page-scroll'> Skills </a>
            </li>
            <li class='nav-item'>
                <a href="{%url 'story2:index' %}#experience"  class='nav-link page-scroll'> Experience </a>
            </li>
            <li class='nav-item'>
                <a href="{%url 'story2:index' %}#education"  class='nav-link page-scroll'> Education </a>
            </li>
            <li class='nav-item'>
                <a href="{%url 'story2:index' %}#projects"  class='nav-link page-scroll'> Projects </a>
            </li>  
        </ul>
        {% endblock %}
        
        
    </nav>

    {% block content %}
    <!--Heading-->
        <div class="container-fluid text-center" style="background-color:#E9ECEF ; min-height: 100vh;">
            <div class="row justify-content-center" >
                <div class="col-12 col-xl-4 col-md-6 mb-4 mb-md-0" style=" padding-top: 150px;">
                    <img src="{% static 'story2/Mask Group.png' %}" alt="">
                </div>
                <div class='col-12 col-xl-4 col-md-6' style="text-align: left; padding-top:10%; ">
                    <h1>Hello, I'm Rafi Muhammad</h1>
                    <p>I am a second year student at Faculty of Computer Science, University of Indonesia. Currently interested with Artificial Intelligence, Data Science, Cyber Security and Software Engineering. Also love art especially filmmaking and I do just for hobby. </p>
                    <button id='explore' type="button" class="btn btn-dark">Explore me!</button>
                    
                </div>
            </div>
            <br>
        </div>

        

    <!--Skills-->
    <div id='skills'>
        <div class="container text-center">
            <div class="row">
                <div class='col col-md-12' style="padding-top:5%; padding-bottom: 0px;">
                    <h1>Skills</h1>
                </div>
            </div>
    
            
    
            <div class="border border-light">
                <h1 style="text-align: left; font-size: large; padding-bottom: 3%; padding-top:3% ">Programing langugae</h1>
                <div class='row justify-content-center' style="padding-bottom: 5% ;">
                    <div class='col col-md-3'>
                        <h3>Python</h3>
                        <div class="progress">
                            <div class="progress-bar" style="width:70%"></div>
                        </div>
                        <p style="text-align: right;">70%</p>
                    </div>
        
                    <div class='col col-md-3'>
                        <h3>Java</h3>
                        <div class="progress">
                            <div class="progress-bar" style="width:70%"></div>
                            
                        </div>
                        <p style="text-align: right;">70%</p>
                    </div>
        
                    <div class='col col-md-3'>
                        <h3>R</h3>
                        <div class="progress">
                            <div class="progress-bar" style="width:40%"></div>
                        </div>
                        <p style="text-align: right;">40%</p>
                    </div>
                </div>
            </div>
    
            <div class="border border-light">
                <h1 style="text-align: left; font-size: large; padding-bottom: 3%; padding-top:3%">Frameworks</h1>
                <div class='row justify-content-center' style="padding-bottom: 5% ;">
                    <div class='col col-md-3'>
                        <h3>Django</h3>
                        <div class="progress">
                            <div class="progress-bar" style="width:50%"></div>
                            
                        </div>
                        <p style="text-align: right;">50%</p>
                    </div>
                    
                    <div class='col col-md-3'>
                        <h3>Pandas</h3>
                        <div class="progress">
                            <div class="progress-bar" style="width:40%"></div>
                            
                        </div>
                        <p style="text-align: right;">40%</p>
                    </div>
    
                    <div class='col col-md-3'>
                        <h3>NumPy</h3>
                        <div class="progress">
                            <div class="progress-bar" style="width:40%"></div>
                            
                        </div>
                        <p style="text-align: right;">40%</p>
                    </div>
    
                    <div class='col col-md-3'>
                        <h3>Seaborn</h3>
                        <div class="progress">
                            <div class="progress-bar" style="width:40%"></div>
                            
                        </div>
                        <p style="text-align: right;">40%</p>
                    </div>
    
                    <div class='col col-md-3'>
                        <h3>Scikit-Learn</h3>
                        <div class="progress">
                            <div class="progress-bar" style="width:40%"></div>
                            
                        </div>
                        <p style="text-align: right;">40%</p>
                    </div>
                </div>
            </div>
    
            <div class="border border-light">
                <h1 style="text-align: left; font-size: large; padding-bottom: 3%; padding-top:3%">Other</h1>
                <div class='row justify-content-center' style="padding-bottom: 5% ;">
                    <div class='col col-md-3'>
                        <h3>Adobe Premiere Pro</h3>
                        <div class="progress">
                            <div class="progress-bar" style="width:70%"></div>
                            
                        </div>
                        <p style="text-align: right;">70%</p>
                    </div>
    
                    <div class='col col-md-3'>
                        <h3>Adobe After Effect</h3>
                        <div class="progress">
                            <div class="progress-bar" style="width:50%"></div>
                            
                        </div>
                        <p style="text-align: right;">50%</p>
                    </div>
                </div>
            </div>
        </div>

    </div>
    
    
    <hr>

    <!-- Experience & Organization-->

    <div id='experience'>
        <div class="container text-center">
            <div class="row">
                <div class='col col-md-12' style="padding-top:5%; padding-bottom: 0px;">
                    <h1>Experience & Organization</h1>
                </div>
            </div>
    
            <div class="border border-light">
                <div class='row' style=" text-align: left;">
                    <div class='col col-md-12'>
                        <h1 style="text-align: left;font-size: x-large; padding-bottom: 0; padding-top:3%">Staff of Seminar - COMPFEST 2020</h1>
                        <p> 2020 - Present </p>
                        <p style="margin: 0%;">I'm responsible for creating seminar for Compfest talk </p>
                        <ul>
                            <li> Responsible for Cybersecurity Seminar</li>
                            <li> Responsible for Artificial Intelligence Seminar</li>
                        </ul> 
                        <hr>  
                    </div> 
                              
                </div>
    
                <div class='row' style=" text-align: left ;">
                    <div class='col col-md-12'>
                        <h1 style="text-align: left;font-size: x-large; padding-bottom: 0; padding-top:3%">Staff of Public Relation - FUKI 2020</h1>
                        <p> 2020 - Present</p>
                        <p style="margin: 0%;">I'm responsible for doing publications for FUKI </p>
                        <ul>
                            <li> Responsible for making publications captions</li>
                            <li> Responsible for Rekursif event</li>
                            <li> Responsible for Memoar event</li>
                            <li> Responsible for Fuki Souvenir program</li>
                        </ul> 
                        <hr>  
                    </div>
                </div>
            </div>
        </div>

    </div>

    <hr>

    <div id="education">
        <div class='container text-center'>
            <div class="row">
                <div class='col col-md-12' style="padding-top:5%; padding-bottom: 0px;">
                    <h1>Education</h1>
                </div>
            </div>
    
            <div class="border border-light">
                <div class='row' style=" text-align: left ;">
    
                    <div class='col-12 col-md-4' style="text-align:center">
                        <img src="{% static 'story2/Signature_FASILKOMUI.png' %} " alt="Fasilkom UI" style="max-width:75% ;width: 250px; margin:5%; padding: 5%;">
                    </div>
    
                    <div class='col-12 col-md-8'>
                        <h1 style="text-align: left;font-size: x-large; padding-bottom: 0; padding-top:3%">Universitas Indonesia - <i>Bachelor of Computer Science</i> </h1>
                        <p> 2020 - Present</p>
                        <p style="margin: 0%;">I'm undergraduate computer science student at Faculty of Computer Science, University of Indonesia </p> 
                          
                    </div>
                    
                </div>
                <hr>
            </div>
    
    
        </div>
    </div>
    
        <hr>

    <div id="projects">
        <div class='container text-center'>
            <div class="row">
                <div class='col col-md-12' style="padding-top:5%; padding-bottom: 0px;">
                    <h1>Side Projects</h1>
                </div>
            </div>
    
            <div class="border border-light">
                <div class='row' style=" text-align: left ;">
    
                    <div class='col-12 col-md-12'>
                        <h1 style="text-align: left;font-size: x-large; padding-bottom: 0; padding-top:3%">Jejak Alumni Sega - <i>Backend Engineer</i> </h1>
                        <p style="margin: 0%;"> I'm making a website that contains data of 103 Highschool’s alumni that are related to the alumni next eduction, so it can be used for juniors who will graduate.
                        </p>
                        <hr>
                    </div>
                    
                    <div class='col-12 col-md-12'>
                        <h1 style="text-align: left;font-size: x-large; padding-bottom: 0; padding-top:3%">Teaser Video for Startup Weekend Indonesia - <i>Videographer</i> </h1>
                        <p style="margin: 0%;">I'm making teaser video for Startup Weekend Indonesia</p>
                        <a href="https://www.instagram.com/p/B_NH9vBA7xi/" > <b>See Projects</b> </a>
                        <hr>
                    </div>
                </div>
            </div>
        </div>
    
    </div>

    <br>
    <br>

    {% endblock %}    
    
    
</body>
</html>